php:
    build: .
    ports: 
        - "80:80"
        - "443:443"
    volumes:
        - .:/var/www/html
    links:
        - db
db:
    image: mariadb
    restart: always
    volumes: 
        - /var/lib/mysql
        - ./db/banco.sql:/docker-entrypoint-initdb.d/banco.sql
    environment:
        - MYSQL_ROOT_PASSWORD=123456789
        - MYSQL_DATABASE=projetoAlunos
    ports:
        - 3306:3306
phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
        - 8080:80
    environment:
        - PMA_ARBITRARY=1
    links: 
        - db